add dtype property to graph
HPI-DeepLearning/ssnn pull request #61
Opened 2018-04-09 15:25 UTC by Bartzi

makes things easier

2018-04-09 15:26 UTC, Jopyth commented on length/tests/data_set_tests/test_data_sets.py
>          assert np.uint8 == batch.labels.data.dtype
Use it here too? :cat:

2018-04-09 15:27 UTC, Jopyth commented on length/tests/data_set_tests/test_data_sets.py
>          assert np.uint8 == batch.labels.data.dtype
and here?

2018-04-09 15:27 UTC, Jopyth commented on length/tests/data_set_tests/test_data_sets.py
>          assert np.uint8 == batch.labels.data.dtype
and here?

2018-04-09 15:27 UTC, Jopyth requested changes
:question:

2018-04-09 15:27 UTC, Jopyth commented on length/tests/data_set_tests/test_data_sets.py
>          assert np.uint8 == batch.labels.data.dtype
and here?

2018-04-10 08:29 UTC, Bartzi commented
done, please review again :smile:

2018-04-10 08:36 UTC, Jopyth approved these changes
:japanese_castle:

2018-04-10 08:51 UTC, merged